### ISSUE TITLE
Please upload a zip file to a github release

### ISSUE THREAD

**Issue by cat-in-136** [diffshare/issue-maps#10]
＿＿＿＿＿_　　　　＿＿_　　＿＿＿＿　　＿＿＿＿_　　　　 ＿_　　 　 ___
　　 /＿＿＿　　　/　　　　|　　／　/　　　　　　|　/＿＿　　**/ [][]　/　 /　　　_|　|_
　　 　 　 　 / 　 / 　　　　/　 /　　/　 /￣￣|.　l　　　　/　/　 　 　 /　 /　　　 |_　　ﾚ'~￣|
　　　　 　 / 　 /. 　　　　/　 /　　/　 /.　　／　/　　　　|　 |_**　　　＼　＼　　　 / 　 ／|　|
　　　 　 / 　 /　　　　　/　 /　　/　　￣￣　／　　　　　＼＿_| 　　　　＼　＼　/_　 /　　|　|_
　 　 　/ 　 /　　 　 　 /　 /　　/　 /￣￣￣　　　　　　　　　　　　　　　　￣￣ 　.|**|　　　＼/
　　　/ 　 /　　　　　 /　 /　　/　 /
　　/ 　 /＿＿**.　 /　 /　　/　 /
　/　　　　　　 / ／　　 |　 /　 /
　￣￣￣￣￣　￣￣￣　　￣
`npm install` したりするの面倒なので、ビルドした結果を zip で置いていただきたい。zip 化は毎ビルドは必要はなく、特定のタイミング (tag) でかまいません。

References:
- [GitHub Releases Uploading - Travis CI](https://docs.travis-ci.com/user/deployment/releases)
- [node-webkitアプリをTravis CI経由でGitHub Releaseにバイナリ登録する - Web Scratch ](http://efcl.info/2014/09/05/node-webkit-binary-release/)

**Comment by cat-in-136** [comment]
FYI: cat-in-136/issue-maps-classic@f1ff73db01e80b8e98010d9965ab3793ae9d6176

**Comment by diffshare** [comment]
@cat-in-136 
対応しました

https://github.com/diffshare/issue-maps/releases/tag/0.1
